# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: Simple build to upload HTML file
- task: AzureCLI@2
  inputs:
    azureSubscription: 'dnourwebapp - 1 - Azure'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload --account-name asadocs --container-name docs --name doc.html --file "docs.html"'

